import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { existsSync, cpSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/**
 * Copy CircuitJS assets to output directory for production builds
 */
async function copyCircuitJsAssets() {
	const srcDir = join(__dirname, "dist", "circuitjs");
	const destDir = join(__dirname, "circuitjs");

	if (!existsSync(srcDir)) {
		console.warn("⚠ CircuitJS assets not found in dist/circuitjs/");
		console.warn("  Run 'npm run build:circuitjs' first for offline mode support");
		return false;
	}

	// Copy assets to root circuitjs/ folder (alongside main.js)
	if (existsSync(destDir)) {
		// Remove existing to ensure clean copy
		const { rmSync } = await import("node:fs");
		rmSync(destDir, { recursive: true, force: true });
	}
	mkdirSync(destDir, { recursive: true });
	cpSync(srcDir, destDir, { recursive: true });
	console.log("✓ Copied CircuitJS assets to circuitjs/");
	return true;
}

// Custom plugin to copy CircuitJS assets after build
const copyCircuitJsPlugin = {
	name: "copy-circuitjs",
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length === 0 && prod) {
				copyCircuitJsAssets();
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyCircuitJsPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
